spring:
  redis:
    timeout: 30000
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100     # 连接池中的最大空闲连接
        min-idle: 20      # 连接池中的最小空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    sentinel:
      master: mymaster
      nodes: 192.168.100.131:26782, 192.168.100.131:26783, 192.168.100.131:26784
    # 密码位于redis配置下
    password: 123456

server:
  port: 8097
