##########################
## Redis-哨兵模式配置-开始##
##########################
#spring:
#  redis:
#    timeout: 30000
#    lettuce:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 100     # 连接池中的最大空闲连接
#        min-idle: 20      # 连接池中的最小空闲连接
#        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    sentinel:
#      master: mymaster
#      nodes: 192.168.100.131:26782, 192.168.100.131:26783, 192.168.100.131:26784
#    # 密码位于redis配置下
#    password: 123456
##########################
## Redis-哨兵模式配置-结束##
##########################


##########################
# Redis-集群模式配置-开始##
##########################
#spring:
#  redis:
#    timeout: 30000
#    lettuce:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接
#        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    cluster:
#      nodes:
#        - 192.168.100.133:6662
#        - 192.168.100.133:6661
#        - 192.168.100.130:6663
#        - 192.168.100.130:6664
#        - 192.168.100.131:6665
#        - 192.168.100.131:6666
##########################
# Redis-集群模式配置-结束##
##########################


##########################
## Redis-单机模式配置-开始##
spring:
  redis:
    timeout: 30000
    host: localhost
    port: 6379
    password: 123456
## Redis-单机模式配置-结束##
##########################

server:
  port: 8097
