server:
  port: 8096
  servlet:
    context-path: /

# QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com              # 发送邮件服务器
    username: 1549148883@qq.com    # 发送邮件的邮箱地址
    password:  ctq*****ed    # 客户端授权码，由qq邮箱设置自动生成
    properties.mail.smtp.port: 587 # 端口号465或587
    from: 1549148883@qq.com        # 发送邮件的地址，和上面username一致
    default-encoding: UTF-8

  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true
  properties.mail.smtp.ssl.enable: true