spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      # primary: master
      # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strict: false
      datasource:
        master:
          jdbc-url: jdbc:mysql://192.168.100.130:3306/springdemo?useUnicode=true&characterEncoding=UTF8&useSSL=true&serverTimezone=Asia/Shanghai
          username: root
          password: aA123456/
          driver-class-name: com.mysql.cj.jdbc.Driver
        mysql:
          url: jdbc:mysql://localhost:3306/employees?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        oracle:
          url: jdbc:mysql://localhost:3306/employees?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

    # druid 数据源配置
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙
      filters: stat,wall,log4j2

      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true

      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #ip白名单
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #ip黑名单
        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true

# 数据库密码 解密秘钥
jasypt:
  encryptor:
    password: demo
